# Generated by Django 5.2.6 on 2025-10-08 07:54

import django.db.models.deletion
import signing.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Documento')),
                ('original_file', models.FileField(upload_to=signing.models.document_upload_path, verbose_name='Ficheiro Original')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SENT', 'Enviado para Assinatura'), ('COMPLETED', 'Concluído'), ('VOIDED', 'Anulado')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signable_documents', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=255, verbose_name='Nome do Signatário')),
                ('signer_email', models.EmailField(max_length=254, verbose_name='Email do Signatário')),
                ('signature_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SIGNED', 'Assinado'), ('DECLINED', 'Recusado')], default='PENDING', max_length=10, verbose_name='Estado da Assinatura')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Assinado em')),
                ('signed_ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('signed_document_file', models.FileField(blank=True, null=True, upload_to='signed_documents/', verbose_name='Ficheiro Assinado')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='signing.signabledocument', verbose_name='Documento')),
            ],
        ),
    ]
