# Generated by Django 5.2.6 on 2025-10-01 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Endereço de e-mail')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='Número do WhatsApp')),
                ('subscription_plan', models.CharField(choices=[('FREE', 'Plano Gratuito'), ('BASIC', 'Plano Básico'), ('PREMIUM', 'Plano Premium')], default='FREE', max_length=10)),
                ('subscription_status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('CANCELED', 'Cancelada'), ('INCOMPLETE', 'Incompleta')], default='INCOMPLETE', max_length=10)),
                ('moloni_access_token', models.CharField(blank=True, max_length=512, null=True)),
                ('moloni_refresh_token', models.CharField(blank=True, max_length=512, null=True)),
                ('moloni_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
