# Generated by Django 5.2.6 on 2025-10-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chatbot_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customuser',
            name='chatbot_state',
            field=models.CharField(blank=True, default='idle', max_length=50),
        ),
    ]
